ninetyninecats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats
  resources :cat_rental_requests

end

ninetyninecats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ninetyninecats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint(8)        not null, primary key
#  name        :string           not null
#  birth_date  :date             not null
#  color       :string
#  sex         :string(1)
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
  COLORS = %w(brown yellow white black calico orange)
  SEX = %w(M F)
  validates :sex, inclusion: SEX
  validates :color, inclusion: COLORS
  validates :name, :birth_date, presence: true

  has_many :cat_rental_requests,
  primary_key: :id,
  foreign_key: :cat_id,
  class_name: :CatRentalRequest,
  dependent: :destroy


  def age
    Time.now.to_s[0..3].to_i - birth_date.to_s[0..3].to_i
  end

end

ninetyninecats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint(8)        not null, primary key
#  cat_id     :integer          not null
#  end_date   :date             not null
#  start_date :date             not null
#  status     :string           default("pending")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord
  validates :status, presence: true, inclusion: ['approved','denied','pending']
  validates :start_date, :end_date, presence: true
  validate :does_not_overlap_approved_request

  belongs_to :cat,
  primary_key: :id,
  foreign_key: :cat_id,
  class_name: :Cat

  def overlapping_requests
    CatRentalRequest.where("cat_id = ?",cat_id).where.not("end_date < ? or start_date > ?",start_date, end_date)
  end

  def overlapping_approved_requests
    overlapping_requests.where( status: 'approved')
  end


  def does_not_overlap_approved_request
    unless overlapping_approved_requests.empty?
      errors[:date_range] << "range overlaps with other approved requests"
    end
  end

end

ninetyninecats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

ninetyninecats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def index
    @all = CatRentalRequest.all
    render :index
  end

  def new
    @crr = CatRentalRequest.new
    render :new
  end

  def edit
    @crr = CatRentalRequest.find(params[:id])
    render :edit
  end

  def show
    @crr = CatRentalRequest.find(params[:id])
    render :show
  end

  def update
    @crr = CatRentalRequest.find(params[:id])
    if @crr.update(crr_params)
      redirect_to cat_rental_request_url(@crr)
    else
      render :edit
    end
  end

  def create
    @crr = CatRentalRequest.new(crr_params)
    if @crr.save
      redirect_to cat_url(@crr.cat_id)
    else
      render json: @crr.errors.full_messages
    end
  end

  private
  def crr_params
    params.require(:cat_rental).permit(:cat_id,:start_date,:end_date)
  end
end

ninetyninecats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
      @cat = Cat.find(params[:id])
      render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:name,:birth_date,:color,:sex,:description)
  end
end

ninetyninecats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninetyninecats/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

ninetyninecats/app/helpers/cats_helper.rb
module CatsHelper
end

ninetyninecats/app/views/cat_rental_requests/_form.html.erb
<% if action == :new%>
<%action_url =  cat_rental_requests_url %>
<% else%>
<% cat_rental_request_url(crr) %>
<%end%>

<form action="<%=action_url%>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  Cat : <br><select name="cat_rental[cat_id]">
    <option disabled <%= 'selected' unless crr.cat_id%>>-- select a cat --</option>
    <% Cat.all.each do |cat| %>
      <option value= <%= cat.id %> ><%=cat.name%></option>
    <% end %>
  </select><br>
  Start Date <input type="date" name="cat_rental[start_date]" value=""><br>
  End Date <input type="date" name="cat_rental[end_date]" value=""><br>
  <input type="submit" value="<%= action == :new ? 'Add your rental to database!' : 'Edit your rental!' %>">

</form>

ninetyninecats/app/views/cat_rental_requests/edit.html.erb
<h1>Edit your rental! 😻</h1>

<%= render 'form', action: :edit, crr: @crr %>

ninetyninecats/app/views/cat_rental_requests/new.html.erb
<h1>Rent a cat! 😻</h1>
<%= render 'form', action: :new, crr: @crr %>

ninetyninecats/app/views/cats/_cat.html.erb
<tr>
  <% if page_origin == :index %>
    <td><a href="<%= cat_url(cat)%>"><%= cat.name %></a></td>
  <% else %>
    <td><%= cat.name %></td>
  <% end %>
  <td><%= cat.age %></td>
  <td><%= cat.birth_date %></td>
  <td><%= cat.color %></td>
  <td><%= cat.sex %></td>
  <td><%= cat.description %></td>
</tr>

ninetyninecats/app/views/cats/_cat_headers.html.erb
  <th>Name</th>
  <th>Age</th>
  <th>birth date</th>
  <th>color</th>
  <th>sex</th>
  <th>description</th>

ninetyninecats/app/views/cats/_form.html.erb
<% if action == :new %>
  <%action_url = cats_url  %>
<% else %>
  <% action_url = cat_url(cat) %>
<% end %>


<form action="<%= action_url%>" method="post"><br>
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  Name : <input type="text" name="cat[name]" value="<%=cat.name%>"><br>
  Sex : <br><input type="radio" name="cat[sex]" value="M" <%="checked" if cat.sex == "M"%> >Male<br>
  <input type="radio" name="cat[sex]" value="F" <%="checked" if cat.sex == "F"%> >Female<br>
  Color : <br><select name="cat[color]">
    <option disabled <%= 'selected unless Cat::COLORS.include?(cat.color)'%>>-- select a color --</option>
    <% Cat::COLORS.each do |color| %>
      <option value="<%=color%>"<%="selected" if cat.color == color %>><%=color%></option>
    <% end %>
  </select><br>
  Birth Date : <br><input type="date" name="cat[birth_date]" <%="value=#{cat.birth_date}"%>><br>
  Description : <br><textarea name="cat[description]" ><%=cat.description%></textarea><br>
  <input type="submit" value="<%= action == :new ? 'Add your cat to database!' : 'Edit your cat!' %>">
</form>

ninetyninecats/app/views/cats/edit.html.erb
<h1>MAKE CHANGES TO YOUR CAT INFO ! 🐈</h1>
<%= render 'form', cat: @cat, action: :edit %>

ninetyninecats/app/views/cats/index.html.erb
<h1>🐈ALL OUR CATS 🐈</h1>
<a href="<%=new_cat_url%>">Add your cat to our database!😻</a>
<table>
  <%= render 'cat_headers' %>
  <% @cats.each do |cat| %>
    <%= render 'cat', cat: cat, page_origin: :index %>
  <% end %>
</table>

ninetyninecats/app/views/cats/new.html.erb
<h1>ADD YOUR CAT TO OUR DATABASE 🐈</h1>
<%= render 'form', cat: @cat, action: :new %>

ninetyninecats/app/views/cats/show.html.erb
<h1>🐈CAT INFO!!🐈</h1>
<p><a href='<%= cats_url %>'>Cats list</a>
<table>
  <%= render 'cat_headers' %>
  <%= render 'cat', cat: @cat, page_origin: :show %>
</table>

ninetyninecats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ninetyninecats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>